const Terms = [
    { term: "POP", full: "Post Office Protocol 3", layer: "Application", description: "用于用户从邮件服务器拉取邮件" },
    { term: "IMAP", full: "Internet Message Access Protocol", layer: "Application", description: "一种邮件协议，允许客户端检索邮件存储在邮件服务器上的邮件" },
    { term: "FTP", full: "File Transfer Protocol", layer: "Application", description: "用于在网络上进行文件传输" },
    { term: "RTP", full: "Real-time Transport Protocol", layer: "Application", description: "用于传送实时数据，如音频或视频" },
    { term: "TFTP", full: "Trivial File Transfer Protocol", layer: "Application", description: "简单的文件传输协议，常用于启动无盘工作站或加载网络设备软件" },
    { term: "Telnet", full: "Teletype over the Network", layer: "Application", description: "用于远程登录到另一台计算机" },
    { term: "DNS", full: "Domain Name System", layer: "Application", description: "将域名转换为IP地址" },
    { term: "SMTP", full: "Simple Mail Transfer Protocol", layer: "Application", description: "用于发送电子邮件的标准协议" },
    { term: "HTTP", full: "HyperText Transfer Protocol", layer: "Application", description: "用于传输超文本标记语言（HTML）" },
    { term: "HTML", full: "HyperText Markup Language", layer: "Application", description: "用于创建网页的标准标记语言" },
    { term: "WWW", full: "World Wide Web", layer: "Application", description: "由相互链接的超文本文档组成的系统" },
    { term: "MIME", full: "Multipurpose Internet Mail Extensions", layer: "Application", description: "扩展SMTP协议，支持多媒体邮件" },
    { term: "CSMA", full: "Carrier Sense Multiple Access", layer: "Data Link", description: "一种介质访问控制协议，用于共享网络媒体" },
    { term: "CSMA/CD", full: "Carrier Sense Multiple Access with Collision Detection", layer: "Data Link", description: "一种介质访问控制技术，用于检测冲突" },
    { term: "CSMA/CA", full: "Carrier Sense Multiple Access with Collision Avoidance", layer: "Data Link", description: "一种用于避免碰撞的技术，常见于无线网络" },
    { term: "CDM", full: "Code Division Multiplexing", layer: "Data Link", description: "一种允许同时共享同一信道的技术" },
    { term: "CDMA", full: "Code Division Multiple Access", layer: "Data Link", description: "一种多址接入技术" },
    { term: "FDM", full: "Frequency Division Multiplexing", layer: "Data Link", description: "一种在同一通道上传输多个信号的技术" },
    { term: "TDM", full: "Time Division Multiplexing", layer: "Data Link", description: "一种通过时间分割来共享信道的技术" },
    { term: "WDM", full: "Wavelength Division Multiplexing", layer: "Data Link", description: "一种利用不同波长来携带多个信号的技术" },
    { term: "PPP", full: "Point-to-Point Protocol", layer: "Data Link", description: "用于通过点对点连接进行数据传输" },
    { term: "HDLC", full: "High-Level Data Link Control", layer: "Data Link", description: "一种设计用于同步网络的数据链路层协议" },
    { term: "VLAN", full: "Virtual Local Area Network", layer: "Data Link", description: "一种逻辑上分割网络的方法" },
    { term: "RTS", full: "Request to Send", layer: "Data Link", description: "用于请求发送数据前的握手信号" },
    { term: "CTS", full: "Clear to Send", layer: "Data Link", description: "用于指示可以发送数据的信号" },
    { term: "MAC", full: "Media Access Control", layer: "Data Link", description: "用于控制网络接口的数据链路层子层" },
    { term: "LLC", full: "Logical Link Control", layer: "Data Link", description: "数据链路层的一部分，负责流量控制和服务选择" },
    { term: "CRC", full: "Cyclic Redundancy Check", layer: "Data Link", description: "用于检测数据传输错误的一种校验方法" },
    { term: "GBN", full: "Go-Back-N", layer: "Data Link", description: "一种用于可靠数据传输的协议" },
    { term: "BGP", full: "Border Gateway Protocol", layer: "Network", description: "用于在不同的自治系统之间交换路由信息" },
    { term: "IGP", full: "Interior Gateway Protocol", layer: "Network", description: "用于在一个自治系统内部交换路由信息" },
    { term: "OSPF", full: "Open Shortest Path First", layer: "Network", description: "一种链路状态路由协议" },
    { term: "RIP", full: "Routing Information Protocol", layer: "Network", description: "一种距离向量路由协议" },
    { term: "ICMP", full: "Internet Control Message Protocol", layer: "Network", description: "用于在网络设备之间传递控制消息" },
    { term: "IGMP", full: "Internet Group Management Protocol", layer: "Network", description: "用于管理组播成员资格" },
    { term: "CIDR", full: "Classless Inter-Domain Routing", layer: "Network", description: "一种用于有效分配IPv4地址的方案" },
    { term: "ARP", full: "Address Resolution Protocol", layer: "Network", description: "用于映射IP地址到物理地址" },
    { term: "DHCP", full: "Dynamic Host Configuration Protocol", layer: "Network", description: "用于自动分配IP地址和其他网络配置参数" },
    { term: "OpenFlow", full: "OpenFlow", layer: "Network", description: "一种网络协议，用于实现软件定义网络(SDN)" },
    { term: "AS", full: "Autonomous System", layer: "Network", description: "互联网中的一个可管理网络" },
    { term: "RSA", full: "Rivest-Shamir-Adleman", layer: "Network Security", description: "一种公钥加密算法" },
    { term: "AES", full: "Advanced Encryption Standard", layer: "Network Security", description: "一种对称密钥加密标准" },
    { term: "PSK", full: "Phase Shift Keying", layer: "Physical", description: "一种数字调制方案" },
    { term: "FSK", full: "Frequency Shift Keying", layer: "Physical", description: "一种数字调制方案" },
    { term: "ASK", full: "Amplitude Shift Keying", layer: "Physical", description: "一种数字调制方案" },
    { term: "QAM", full: "Quadrature Amplitude Modulation", layer: "Physical", description: "一种混合幅度和相位调制的方案" },
    { term: "PIM", full: "Protocol Independent Multicast", layer: "Network", description: "一种组播路由协议" },
    { term: "NRZ", full: "Non-Return to Zero", layer: "Physical", description: "一种用于表示二进制数据的编码方案" },
    { term: "RZ", full: "Return to Zero", layer: "Physical", description: "一种用于表示二进制数据的编码方案" },
    { term: "NRZI", full: "Non-Return to Zero Inverted", layer: "Physical", description: "一种编码方案，其中逻辑1不会改变线路电压" },
    { term: "PCM", full: "Pulse Code Modulation", layer: "Physical", description: "一种模拟信号数字化的编码方式" },
    { term: "TCP", full: "Transmission Control Protocol", layer: "Transport", description: "一种面向连接的、可靠的、基于字节流的传输层通信协议" },
    { term: "UDP", full: "User Datagram Protocol", layer: "Transport", description: "一种无连接的传输层协议，提供不可靠的数据报传输" },
    { term: "cwnd", full: "Congestion Window", layer: "Transport", description: "TCP拥塞控制中的一个概念，用来控制发送速率" },
    { term: "MSS", full: "Maximum Segment Size", layer: "Transport", description: "TCP的最大段大小，定义了单个TCP报文段能够携带的最大数据量" },
    { term: "SDLC", full: "Synchronous Data Link Control", layer: "Data Link", description: "同步数据链路控制" },
    { term: "PAN", full: "Personal Area Network", layer: "", description: "一种用于连接个人空间内的设备的网络" },
    { term: "LAN", full: "Local Area Network", layer: "", description: "一种连接相对小区域内的设备的网络" },
    { term: "PDU", full: "Protocol Data Unit", layer: "", description: "在网络协议栈的每一层传输的数据单位" },
    { term: "SDU", full: "Service Data Unit", layer: "", description: "服务访问点上呈现的数据单元" },
    { term: "AP", full: "Access Point", layer: "", description: "一种无线网络设备，用于无线设备连接到有线网络" },
    { term: "NAT", full: "Network Address Translation", layer: "Network", description: "一种用于重写IP地址的技术" },
    { term: "TTL", full: "Time To Live", layer: "Network", description: "数据包在网络中存活的时间" },
    { term: "SAP", full: "Service Access Point", layer: "", description: "网络层的服务访问点" }
];

export default Terms;