const Terms = [
    { term: "POP", full: "Post Office Protocol 3", layer: "Application", link: "郵局協定", description: "用于用户从邮件服务器拉取邮件" },
    { term: "IMAP", full: "Internet Message Access Protocol", layer: "Application", link: "因特网信息访问协议", description: "一种邮件协议，允许客户端检索邮件存储在邮件服务器上的邮件" },
    { term: "FTP", full: "File Transfer Protocol", layer: "Application", link: "文件传输协议", description: "用于在网络上进行文件传输" },
    { term: "RTP", full: "Real-time Transport Protocol", layer: "Application", link: "实时传输协议", description: "用于传送实时数据，如音频或视频" },
    { term: "TFTP", full: "Trivial File Transfer Protocol", layer: "Application", link: "简单文件传输协议", description: "简单的文件传输协议，常用于启动无盘工作站或加载网络设备软件" },
    { term: "Telnet", full: "Teletype over the Network", layer: "Application", link: "Telnet", description: "用于远程登录到另一台计算机" },
    { term: "DNS", full: "Domain Name System", layer: "Application", link: "域名系统", description: "将域名转换为IP地址" },
    { term: "SMTP", full: "Simple Mail Transfer Protocol", layer: "Application", link: "简单邮件传输协议", description: "用于发送电子邮件的标准协议" },
    { term: "HTTP", full: "HyperText Transfer Protocol", layer: "Application", link: "超文本传输协议", description: "用于传输超文本标记语言（HTML）" },
    { term: "HTML", full: "HyperText Markup Language", layer: "Application", link: "HTML", description: "用于创建网页的标准标记语言" },
    { term: "WWW", full: "World Wide Web", layer: "Application", link: "万维网", description: "由相互链接的超文本文档组成的系统" },
    { term: "MIME", full: "Multipurpose Internet Mail Extensions", layer: "Application", link: "多用途互聯網郵件擴展", description: "扩展SMTP协议，支持多媒体邮件" },
    { term: "CSMA", full: "Carrier Sense Multiple Access", layer: "Data Link", link: "载波侦听多路访问", description: "一种介质访问控制协议，用于共享网络媒体" },
    { term: "CSMA/CD", full: "Carrier Sense Multiple Access with Collision Detection", layer: "Data Link", link: "载波侦听多路访问", description: "一种介质访问控制技术，用于检测冲突" },
    { term: "CSMA/CA", full: "Carrier Sense Multiple Access with Collision Avoidance", layer: "Data Link", link: "载波侦听多路访问", description: "一种用于避免碰撞的技术，常见于无线网络" },
    { term: "CDM", full: "Code Division Multiplexing", layer: "Data Link", link: "分碼多重進接", description: "一种允许同时共享同一信道的技术" },
    { term: "CDMA", full: "Code Division Multiple Access", layer: "Data Link", link: "分碼多重進接", description: "一种多址接入技术" },
    { term: "FDM", full: "Frequency Division Multiplexing", layer: "Data Link", link: "频分多路复用", description: "一种在同一通道上传输多个信号的技术" },
    { term: "TDM", full: "Time Division Multiplexing", layer: "Data Link", link: "时分多路复用", description: "一种通过时间分割来共享信道的技术" },
    { term: "WDM", full: "Wavelength Division Multiplexing", layer: "Data Link", link: "波分复用", description: "一种利用不同波长来携带多个信号的技术" },
    { term: "PPP", full: "Point-to-Point Protocol", layer: "Data Link", link: "点对点协议", description: "用于通过点对点连接进行数据传输" },
    { term: "HDLC", full: "High-Level Data Link Control", layer: "Data Link", link: "高级数据链路控制", description: "一种设计用于同步网络的数据链路层协议" },
    { term: "VLAN", full: "Virtual Local Area Network", layer: "Data Link", link: "虚拟局域网", description: "一种逻辑上分割网络的方法" },
    { term: "RTS", full: "Request to Send", layer: "Data Link", link: "载波侦听多路访问", description: "用于请求发送数据前的握手信号" },
    { term: "CTS", full: "Clear to Send", layer: "Data Link", link: "载波侦听多路访问", description: "用于指示可以发送数据的信号" },
    { term: "MAC", full: "Media Access Control", layer: "Data Link", link: "介质访问控制", description: "用于控制网络接口的数据链路层子层" },
    { term: "LLC", full: "Logical Link Control", layer: "Data Link", link: "逻辑链路控制", description: "数据链路层的一部分，负责流量控制和服务选择" },
    { term: "CRC", full: "Cyclic Redundancy Check", layer: "Data Link", link: "循環冗餘校驗", description: "用于检测数据传输错误的一种校验方法" },
    { term: "GBN", full: "Go-Back-N", layer: "Data Link", link: "Go-Back-N_ARQ", description: "一种用于可靠数据传输的协议" },
    { term: "BGP", full: "Border Gateway Protocol", layer: "Network", link: "边界网关协议", description: "用于在不同的自治系统之间交换路由信息" },
    { term: "IGP", full: "Interior Gateway Protocol", layer: "Network", link: "内部网关协议", description: "用于在一个自治系统内部交换路由信息" },
    { term: "OSPF", full: "Open Shortest Path First", layer: "Network", link: "开放式最短路径优先", description: "一种链路状态路由协议" },
    { term: "RIP", full: "Routing Information Protocol", layer: "Network", link: "路由信息协议", description: "一种距离向量路由协议" },
    { term: "ICMP", full: "Internet Control Message Protocol", layer: "Network", link: "互联网控制消息协议", description: "用于在网络设备之间传递控制消息" },
    { term: "IGMP", full: "Internet Group Management Protocol", layer: "Network", link: "因特网组管理协议", description: "用于管理组播成员资格" },
    { term: "CIDR", full: "Classless Inter-Domain Routing", layer: "Network", link: "无类别域间路由", description: "一种用于有效分配IPv4地址的方案" },
    { term: "ARP", full: "Address Resolution Protocol", layer: "Network", link: "地址解析协议", description: "用于映射IP地址到物理地址" },
    { term: "DHCP", full: "Dynamic Host Configuration Protocol", layer: "Network", link: "动态主机设置协议", description: "用于自动分配IP地址和其他网络配置参数" },
    { term: "OpenFlow", full: "OpenFlow", layer: "Network", link: "OpenFlow", description: "一种网络协议，用于实现软件定义网络(SDN)" },
    { term: "AS", full: "Autonomous System", layer: "Network", link: "自治系统", description: "互联网中的一个可管理网络" },
    { term: "RSA", full: "Rivest-Shamir-Adleman", layer: "Network Security", link: "RSA加密演算法", description: "一种公钥加密算法" },
    { term: "AES", full: "Advanced Encryption Standard", layer: "Network Security", link: "高级加密标准", description: "一种对称密钥加密标准" },
    { term: "PSK", full: "Phase Shift Keying", layer: "Physical", link: "相位偏移調變", description: "一种数字调制方案" },
    { term: "FSK", full: "Frequency Shift Keying", layer: "Physical", link: "頻率偏移調變", description: "一种数字调制方案" },
    { term: "ASK", full: "Amplitude Shift Keying", layer: "Physical", link: "幅移键控", description: "一种数字调制方案" },
    { term: "QAM", full: "Quadrature Amplitude Modulation", layer: "Physical", link: "正交幅度调制", description: "一种混合幅度和相位调制的方案" },
    { term: "PIM", full: "Protocol Independent Multicast", layer: "Network", link: "独立组播协议", description: "一种组播路由协议" },
    { term: "NRZ", full: "Non-Return to Zero", layer: "Physical", link: "不歸零_(信號)", description: "一种用于表示二进制数据的编码方案" },
    { term: "RZ", full: "Return to Zero", layer: "Physical", link: "不歸零_(信號)", description: "一种用于表示二进制数据的编码方案" },
    { term: "NRZI", full: "Non-Return to Zero Inverted", layer: "Physical", link: "不歸零_(信號)", description: "一种编码方案，其中逻辑1不会改变线路电压" },
    { term: "PCM", full: "Pulse Code Modulation", layer: "Physical", link: "脈衝編碼調變", description: "一种模拟信号数字化的编码方式" },
    { term: "TCP", full: "Transmission Control Protocol", layer: "Transport", link: "传输控制协议", description: "一种面向连接的、可靠的、基于字节流的传输层通信协议" },
    { term: "UDP", full: "User Datagram Protocol", layer: "Transport", link: "用户数据报协议", description: "一种无连接的传输层协议，提供不可靠的数据报传输" },
    { term: "cwnd", full: "Congestion Window", layer: "Transport", link: "拥塞控制", description: "TCP拥塞控制中的一个概念，用来控制发送速率" },
    { term: "MSS", full: "Maximum Segment Size", layer: "Transport", link: "最大分段大小", description: "TCP的最大段大小，定义了单个TCP报文段能够携带的最大数据量" },
    { term: "SDLC", full: "Synchronous Data Link Control", layer: "Data Link", link: "高级数据链路控制", description: "同步数据链路控制" },
    { term: "PAN", full: "Personal Area Network", layer: "", link: "局域网", description: "一种用于连接个人空间内的设备的网络" },
    { term: "LAN", full: "Local Area Network", layer: "", link: "局域网", description: "一种连接相对小区域内的设备的网络" },
    { term: "PDU", full: "Protocol Data Unit", layer: "", link: "协议数据单元", description: "在网络协议栈的每一层传输的数据单位" },
    { term: "SDU", full: "Service Data Unit", layer: "", link: "", description: "服务访问点上呈现的数据单元" },
    { term: "AP", full: "Access Point", layer: "", link: "無線接入點", description: "一种无线网络设备，用于无线设备连接到有线网络" },
    { term: "NAT", full: "Network Address Translation", layer: "Network", link: "网络地址转换", description: "一种用于重写IP地址的技术" },
    { term: "TTL", full: "Time To Live", layer: "Network", link: "存活時間", description: "数据包在网络中存活的时间" },
    { term: "SAP", full: "Service Access Point", layer: "", link: "無線接入點", description: "网络层的服务访问点" }
];

export const termColumns = [
    {
        title: '术语缩写',
        dataIndex: 'term',
        key: 'term',
        render: (text, record) => (
            <a href={`https://zh.wikipedia.org/wiki/${record.link}`} target="_blank" rel="noopener noreferrer">
                {text}
            </a>
        ),
        sorter: (a, b) => a.term > b.term,
    }, {
        title: '全称',
        dataIndex: 'full',
        key: 'full',
    }, {
        title: '所属层级',
        key: 'layers',
        dataIndex: 'layer',
        sorter: (a, b) => a.layer > b.layer,
    }, {
        title: '描述',
        dataIndex: 'description',
        key: 'description',
    },
];

export default Terms;